from adafruit_pioasm import Program

GPIO_COUNT = 23

OUTPUT = "an.py"


SRC = f"""
.program an
.origin 0

    ; Prime the OSR once. Auto-pull supplies one 32-bit DMA word for every
    ; bit time after this first word.
    pull block
.wrap_target
    ; Each word is the complete GPIO output value for one UART bit.
    ; One instruction is one serial bit time.
    out pins, {GPIO_COUNT}
.wrap
"""


def write_module(path, program):
    opcodes = ", ".join(f"0x{opcode:04x}" for opcode in program.assembled)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by gen.py. Do not edit by hand.\n")
        f.write("import array\n\n")
        f.write(f"GPIO_COUNT = {GPIO_COUNT}\n")
        f.write(f"PROGRAM = array.array('H', [{opcodes}])\n")
        f.write(f"PIO_KWARGS = {program.pio_kwargs!r}\n")


program = Program(SRC)
write_module(OUTPUT, program)
print(f"wrote {OUTPUT}")
